const Router=require('express')
const {sn, ss, sp, snick, sdate, getUser} =require('../controllers/profileController')
const routes = require('../routes')
const tokenValid=require('../middlewares/tokenValid')
const router= new Router()
router.post(routes.profile.sn,tokenValid,sn)
router.post(routes.profile.ss,tokenValid,ss)
router.post(routes.profile.sp,tokenValid,sp)
router.post(routes.profile.snick,tokenValid,snick)
router.post(routes.profile.sdate,tokenValid,sdate)
router.get(routes.profile.getInfo,tokenValid,getUser)
module.exports=router